
version: '3.0'
services:
  web:
    image: michal1115/io-lab-docker-ci-public-master:latest
    ports:
      - 5000:5000
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6.0-rc3
    volumes:
      - ./code:/code:z
